# 选择你要使用的 docker 镜像
image: node:lts

pages:
  # 每当 push 到 main 分支时触发部署
  only:
    - main

  # 缓存 node_modules
  cache:
    key:
      files:
        - yarn-lock.yaml
    paths:
      - .yarn-store

  # 安装 yarn
  before_script:
    - corepack enable
    - yarn config set store-dir .yarn-store

  # 安装依赖并运行构建脚本
  script:
    - yarn install
    - yarn build
    - mv dist public

  artifacts:
    paths:
      - public